trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  solution: '**/*.sln'
  buildPlatform: 'DX12 x64'
  buildConfiguration: 'Release'

steps:

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'Stora Spel SonarCloud'
    organization: 'bth-storaspel-dxr'
    scannerMode: 'MSBuild'
    projectKey: 'bth-storaspel-dxr'
    projectName: 'Game'

- script: git submodule update --init --recursive
  displayName: 'Fetch git submodules'

- script: .\premake\premake5.exe vs2019
  displayName: 'Run premake'

- task: VSBuild@1
  inputs:
    solution: 'Sail.sln'
    vsVersion: '16.0'
    platform: 'DX12 x64'
    configuration: 'Release'
    maximumCpuCount: true
    msbuildArchitecture: 'x64'

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'